'use client'

import { useEffect, useState } from 'react'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Sheet, SheetClose, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ArrowRight, BarChart3, BookOpen, Building2, Check, ChevronRight, CircleDollarSign, ClipboardList, Download, FileSpreadsheet, FileText, HandCoins, Landmark, LayoutDashboard, Menu, Moon, Receipt, ShieldCheck, Sparkles, Sun, Tags, TrendingUp, Send, Users, WalletCards, X } from 'lucide-react'

const features = [
  ['Plot inventory', 'Know what is available, reserved, or sold at a glance.', LayoutDashboard, 'lg:col-span-2'],
  ['Deals & installments', 'Build flexible plans and keep every promise visible.', HandCoins, ''],
  ['Payments & receipts', 'Record collections and issue polished receipts fast.', Receipt, ''],
  ['Payment slip records', 'Never lose a slip, reference number, or follow-up.', ClipboardList, ''],
  ['Investors & profit split', 'Give partners a clear view of their share.', Users, 'lg:col-span-2'],
  ['Loans & finance ledger', 'Track financing alongside land and cash flow.', Landmark, ''],
  ['Dealer exchanges', 'Manage referrals and exchanges without spreadsheet chaos.', Tags, ''],
  ['Reports & exports', 'Turn your ledger into PDF and Excel-ready reports.', Download, 'lg:col-span-2'],
] as const

const faqs = [
  ['Is my data secure?', 'Your workspace is private by default, with role-based access so each person sees only what they need.'],
  ['Can I set different roles?', 'Yes. Invite owners, accountants, and sales agents with focused permissions.'],
  ['Can I import from Excel?', 'Yes. Bring in your existing plot inventory and payment records, then keep everything current in one place.'],
  ['Does Plot Ledge work on mobile?', 'Absolutely. The ledger is responsive and designed for quick updates from the site, office, or a client meeting.'],
  ['Are backups included?', 'Growth and Enterprise include automated backups and export tools so your records stay portable.'],
]

const iconProps = { viewBox: '0 0 24 24', className: 'size-4', 'aria-hidden': true } as const
const LinkedinIcon = () => <svg {...iconProps} fill="currentColor"><path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.35V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12zM7.12 20.45H3.56V9h3.56v11.45z" /></svg>
const XIcon = () => <svg {...iconProps} fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" /></svg>
const InstagramIcon = () => <svg {...iconProps} fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none" /></svg>

function Logo({ inverse = false }: { inverse?: boolean }) {
  return <a href="#top" className={`flex items-center gap-2 font-bold tracking-tight ${inverse ? 'text-white' : 'text-foreground'}`} aria-label="Plot Ledge home"><span className="relative grid size-9 place-items-center rounded-xl bg-emerald-900 text-amber-400 shadow-sm"><svg viewBox="0 0 28 28" className="size-6 fill-none stroke-current" strokeWidth="1.5" aria-hidden="true"><path d="M5 5h18v18H5zM14 5v18M5 14h18" /><path d="M8 8h3v3H8z" className="fill-current" /></svg></span><span>Plot Ledge</span></a>
}

function Status({ children }: { children: string }) {
  const styles = children === 'Paid' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300' : children === 'Overdue' ? 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300' : 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300'
  return <Badge variant="secondary" className={`${styles} border-0`}>{children}</Badge>
}

function DashboardMockup() {
  return <div className="dashboard-float relative mx-auto max-w-xl rounded-3xl border border-white/10 bg-[#10281d] p-3 shadow-2xl shadow-emerald-950/25 sm:p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-2 text-xs text-white/60"><span className="size-2 rounded-full bg-amber-400" /> Overview</div><div className="flex gap-1.5"><span className="size-2 rounded-full bg-white/20" /><span className="size-2 rounded-full bg-white/20" /><span className="size-2 rounded-full bg-white/20" /></div></div><div className="grid grid-cols-3 gap-2 py-4 sm:gap-3"><MiniStat label="Total sales" value="Rs 4.82Cr" /><MiniStat label="Received" value="Rs 3.16Cr" positive /><MiniStat label="Outstanding" value="Rs 1.66Cr" /></div><div className="grid gap-3 sm:grid-cols-[1.05fr_.95fr]"><div className="rounded-2xl bg-white/[.07] p-3"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-medium text-white/70">Collections</span><span className="text-[10px] text-emerald-300">+18.6%</span></div><div className="flex h-28 items-end justify-between gap-2">{[38, 52, 42, 70, 58, 76, 92].map((height, i) => <div key={i} className="w-full rounded-t bg-gradient-to-t from-emerald-500 to-amber-300" style={{ height: `${height}%`, opacity: i === 6 ? 1 : .62 }} />)}</div><div className="mt-2 flex justify-between text-[9px] text-white/40"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span></div></div><div className="rounded-2xl bg-white/[.07] p-3"><span className="text-xs font-medium text-white/70">Recent payments</span><div className="mt-3 flex flex-col gap-3">{[['A-104', 'Rs 85,000', 'Paid', '10:32 AM'], ['B-022', 'Rs 42,500', 'Pending', '09:15 AM'], ['C-018', 'Rs 1,20,000', 'Paid', 'Yesterday']].map(([plot, amount, status, time]) => <div key={plot} className="flex items-center justify-between text-[11px]"><div><p className="font-medium text-white">Plot {plot}</p><p className="text-white/40">{time}</p></div><div className="text-right"><p className="font-semibold text-white">{amount}</p><p className={status === 'Paid' ? 'text-emerald-300' : 'text-amber-300'}>{status}</p></div></div>)}</div></div></div></div>
}

function MiniStat({ label, value, positive = false }: { label: string; value: string; positive?: boolean }) { return <div className="rounded-2xl bg-white/[.07] p-2.5 sm:p-3"><p className="text-[9px] uppercase tracking-wider text-white/40">{label}</p><p className="mt-1 text-sm font-semibold text-white sm:text-base">{value}</p><p className={`mt-1 text-[9px] ${positive ? 'text-emerald-300' : 'text-white/40'}`}>{positive ? '↑ 12.4%' : 'This quarter'}</p></div> }

export default function Page() {
  const [dark, setDark] = useState(false)
  const [annual, setAnnual] = useState(true)
  const [ledgerIndex, setLedgerIndex] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)
  const statuses = ['Paid', 'Pending', 'Overdue']
  useEffect(() => {
    try {
      const saved = localStorage.getItem('theme')
      setDark(saved ? saved === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches)
    } catch { /* storage unavailable: stay light */ }
  }, [])
  const toggleDark = () => {
    const next = !dark
    setDark(next)
    try { localStorage.setItem('theme', next ? 'dark' : 'light') } catch { /* ignore */ }
  }
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  useEffect(() => { const els = document.querySelectorAll('.reveal'); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible') }), { threshold: .12 }); els.forEach(el => observer.observe(el)); return () => observer.disconnect() }, [])
  return <div id="top" className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground lg:flex"><a href="#features" className="transition-colors hover:text-foreground">Features</a><a href="#how" className="transition-colors hover:text-foreground">How it works</a><a href="#pricing" className="transition-colors hover:text-foreground">Pricing</a><a href="#faq" className="transition-colors hover:text-foreground">FAQ</a></nav><div className="hidden items-center gap-2 sm:flex"><Button variant="ghost" nativeButton={false} render={<a href="#" />}>Log in</Button><Button nativeButton={false} render={<a href="#" />} className="bg-amber-500 text-emerald-950 hover:bg-amber-400">Get started free <ArrowRight data-icon="inline-end" /></Button><Button variant="ghost" size="icon" aria-label="Toggle dark mode" onClick={toggleDark}>{dark ? <Sun /> : <Moon />}</Button></div><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger render={<Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu" />}><Menu /></SheetTrigger><SheetContent className="p-0" showCloseButton={false} initialFocus={() => document.getElementById('sheet-close')}><SheetHeader className="flex-row items-center justify-between border-b border-border px-6 py-4"><SheetTitle><Logo /></SheetTitle><SheetClose render={<Button id="sheet-close" variant="ghost" size="icon" className="size-11 shrink-0 rounded-xl focus-visible:ring-2" aria-label="Close menu" />}><X /></SheetClose></SheetHeader><nav className="flex flex-col gap-1 px-6 py-5 text-lg"><a className="rounded-lg py-2.5" href="#features" onClick={() => setMenuOpen(false)}>Features</a><a className="rounded-lg py-2.5" href="#how" onClick={() => setMenuOpen(false)}>How it works</a><a className="rounded-lg py-2.5" href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a><a className="rounded-lg py-2.5" href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><a className="rounded-lg py-2.5" href="#" onClick={() => setMenuOpen(false)}>Log in</a><div className="flex items-center justify-between py-2.5"><span>Dark mode</span><Button variant="ghost" size="icon" aria-label="Toggle dark mode" onClick={toggleDark}>{dark ? <Sun /> : <Moon />}</Button></div><Button nativeButton={false} render={<a href="#" />} className="mt-3 w-full bg-amber-500 text-emerald-950 hover:bg-amber-400" onClick={() => setMenuOpen(false)}>Get started free</Button></nav></SheetContent></Sheet></div></header>
    <main>
      <section className="hero-grid relative"><div className="absolute inset-0 -z-10 overflow-hidden"><div className="absolute left-[5%] top-10 size-72 rounded-full bg-emerald-500/10 blur-3xl" /><div className="absolute right-0 top-32 size-96 rounded-full bg-amber-400/10 blur-3xl" /></div><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 sm:py-28 lg:grid-cols-[.93fr_1.07fr] lg:px-8 lg:py-32"><div className="reveal is-visible"><Badge variant="outline" className="mb-6 rounded-full border-emerald-200 bg-emerald-50 px-3 py-1 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-300"><Sparkles className="mr-1" /> Built for land businesses</Badge><h1 className="max-w-2xl text-5xl font-bold tracking-[-.055em] text-foreground sm:text-6xl lg:text-7xl">Run your plot business <span className="text-emerald-700 dark:text-emerald-400">from one ledger.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Track inventory, deals, installments, slips, and investors without chasing spreadsheets or scattered WhatsApp threads.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" nativeButton={false} render={<a href="#" />} className="bg-amber-500 text-emerald-950 hover:bg-amber-400">Start free <ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" nativeButton={false} render={<a href="#demo" />}><span className="mr-2 grid size-6 place-items-center rounded-full bg-emerald-100 text-emerald-800"><span className="ml-0.5">▶</span></span> Watch demo</Button></div><p className="mt-8 flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="text-emerald-600" /> Built for developers, dealers and accountants</p></div><div className="reveal reveal-delay is-visible" id="demo"><DashboardMockup /></div></div></section>
      <section className="border-y border-border/70 bg-card"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-border px-4 py-8 sm:grid-cols-4 sm:px-6 lg:px-8">{[['2,400+', 'Plots tracked'], ['Rs 18Cr+', 'Payments recorded'], ['680+', 'Deals closed'], ['99.5%', 'Uptime']].map(([num, label]) => <div key={String(label)} className="px-3 text-center first:pl-0 last:pr-0"><p className="text-2xl font-bold tracking-tight text-emerald-800 dark:text-emerald-400 sm:text-3xl">{num}</p><p className="mt-1 text-xs text-muted-foreground sm:text-sm">{label}</p></div>)}</div></section>
      <section id="features" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="reveal max-w-2xl"><p className="eyebrow">Everything in one place</p><h2 className="section-title">Your land business, <span>finally legible.</span></h2><p className="mt-5 text-lg text-muted-foreground">Plot Ledge turns the moving parts of property sales into a calm, shared system your team can trust.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([title, desc, Icon, span], i) => <Card key={String(title)} className={`reveal feature-card border-border/80 bg-card shadow-sm ${span} ${i % 3 === 0 ? 'lg:min-h-60' : ''}`}><CardHeader><div className="mb-4 grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"><Icon /></div><CardTitle className="text-xl">{title}</CardTitle><CardDescription className="text-sm leading-6">{desc}</CardDescription></CardHeader></Card>)}</div></section>
      <section id="how" className="bg-emerald-950 text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="reveal max-w-2xl"><p className="eyebrow text-amber-300">A simpler rhythm</p><h2 className="section-title text-white">From plot list to paid <span className="text-amber-300">in three steps.</span></h2></div><div className="relative mt-14 grid gap-10 md:grid-cols-3 md:gap-8"><div className="absolute left-[16%] right-[16%] top-6 hidden h-px bg-emerald-700 md:block" />{[['01', 'Add your inventory', 'Map plots, prices, statuses, and all the details your team needs.'], ['02', 'Create deals & plans', 'Set buyers, payment schedules, discounts, and partner splits.'], ['03', 'Track every payment', 'Record collections, send receipts, and see what is due next.']].map(([num, title, desc]) => <div key={num} className="reveal relative"><div className="mb-6 grid size-12 place-items-center rounded-2xl border border-amber-400/50 bg-amber-400 text-lg font-bold text-emerald-950">{num}</div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 max-w-xs leading-7 text-emerald-100/70">{desc}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="reveal mb-10 max-w-2xl"><p className="eyebrow">Made for every seat</p><h2 className="section-title">One source of truth. <span>Three ways to work.</span></h2></div><Tabs defaultValue="owner" className="reveal"><TabsList className="mb-8 h-auto w-full justify-start gap-2 rounded-none border-b border-border bg-transparent p-0"><TabsTrigger value="owner">Owner</TabsTrigger><TabsTrigger value="accountant">Accountant</TabsTrigger><TabsTrigger value="agent">Sales Agent</TabsTrigger></TabsList>{[['owner', 'The whole picture, without the whole headache.', 'See inventory health, collections, outstanding balances, and partner performance in one owner dashboard.', ['Portfolio overview', 'Team permissions', 'Profit & loss snapshots'], ['This month', 'Rs 68.4L', 'collected across 42 active plans', '74', '74% of target']], ['accountant', 'Clean books, faster close.', 'Reconcile payments and slips with confidence, then export reports that are ready for review.', ['Payment reconciliation', 'Receipts & ledgers', 'Excel / PDF exports'], ['This week', '18 slips', 'awaiting a match to receipts', '62', '62% reconciled']], ['agent', 'Every lead, deal, and follow-up in reach.', 'Give your sales team the context to move buyers forward without exposing sensitive finance data.', ['Plot availability', 'Buyer timelines', 'Follow-up reminders'], ['Open inventory', '148 plots', 'available across your projects', '41', '41% of booking target']]].map(([value, heading, desc, items, panel]) => <TabsContent key={String(value)} value={String(value)}><div className="grid gap-10 rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-10 md:grid-cols-[1fr_1fr] md:items-center"><div><h3 className="text-3xl font-bold tracking-tight">{heading}</h3><p className="mt-4 max-w-lg leading-7 text-muted-foreground">{desc}</p><ul className="mt-7 flex flex-col gap-3 text-sm font-medium">{(items as string[]).map(item => <li key={item} className="flex items-center gap-3"><span className="grid size-6 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check /></span>{item}</li>)}</ul></div><div className="rounded-2xl bg-emerald-950 p-5 text-white"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-sm text-white/60">{(panel as string[])[0]}</span><TrendingUp className="text-amber-300" /></div><p className="mt-5 text-4xl font-bold">{(panel as string[])[1]}</p><p className="mt-1 text-sm text-emerald-200/70">{(panel as string[])[2]}</p><div className="mt-8 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-amber-400" style={{ width: `${(panel as string[])[3]}%` }} /></div><div className="mt-2 flex justify-between text-xs text-white/50"><span>{(panel as string[])[4]}</span></div></div></div></TabsContent>)}</Tabs></section>
      <section className="bg-secondary/40"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="reveal flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">A ledger you can feel</p><h2 className="section-title">Every line tells you <span>what happens next.</span></h2></div><Button variant="outline" className="w-fit" onClick={() => setLedgerIndex((ledgerIndex + 1) % 3)}>Cycle statuses <ChevronRight data-icon="inline-end" /></Button></div><div className="reveal mt-10 overflow-x-auto rounded-3xl border border-border bg-card shadow-sm"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-border bg-secondary/50 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-6 py-4">Plot / buyer</th><th className="px-6 py-4">Due date</th><th className="px-6 py-4">Amount</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Action</th></tr></thead><tbody>{[['A-104 · Ayesha Khan', '15 Jul 2026', 'Rs 85,000'], ['B-022 · Hamza Qureshi', '20 Jul 2026', 'Rs 42,500'], ['C-018 · Mehwish Ahmed', '28 Jul 2026', 'Rs 1,20,000'], ['D-006 · Bilal Raza', '02 Aug 2026', 'Rs 65,000']].map(([name, date, amount], i) => <tr key={name} className="border-b border-border/70 transition-colors last:border-0 hover:bg-emerald-50/60 dark:hover:bg-emerald-950/30"><td className="px-6 py-5 font-medium">{name}</td><td className="px-6 py-5 text-muted-foreground">{date}</td><td className="px-6 py-5 font-medium">{amount}</td><td className="px-6 py-5"><Status>{statuses[(i + ledgerIndex) % 3]}</Status></td><td className="px-6 py-5 text-emerald-700 dark:text-emerald-400">View <ArrowRight className="ml-1 inline size-4" /></td></tr>)}</tbody></table></div></div></section>
      <section id="pricing" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="reveal mx-auto max-w-2xl text-center"><p className="eyebrow">Pricing that grows with you</p><h2 className="section-title">Start simple. <span>Scale with confidence.</span></h2><div className="mt-7 inline-flex items-center rounded-full border border-border bg-card p-1"><button onClick={() => setAnnual(false)} className={`rounded-full px-4 py-2 text-sm ${!annual ? 'bg-emerald-900 text-white' : 'text-muted-foreground'}`}>Monthly</button><button onClick={() => setAnnual(true)} className={`rounded-full px-4 py-2 text-sm ${annual ? 'bg-emerald-900 text-white' : 'text-muted-foreground'}`}>Yearly <span className={`ml-1 font-semibold ${annual ? 'text-amber-300' : 'text-amber-700 dark:text-amber-400'}`}>Save 20%</span></button></div></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['Starter', 'Free', 'For getting your first plots under control.', ['Up to 25 plots', 'Basic payment ledger', '1 team member']], ['Growth', annual ? 'Rs 28,788 / year' : 'Rs 2,999', 'For teams selling and collecting at scale.', ['Unlimited plots', 'Installments & receipts', '5 team members', 'Reports & exports']], ['Enterprise', 'Let’s talk', 'For housing societies and multi-project teams.', ['Everything in Growth', 'Unlimited team members', 'Priority support']]].map(([name, price, desc, items], i) => <Card key={String(name)} className={`reveal relative overflow-visible ${i === 1 ? 'border-amber-400 bg-amber-50/70 shadow-xl shadow-amber-950/10 dark:bg-emerald-950/40' : 'border-border'}`}>{i === 1 && <div className="absolute left-1/2 -top-3 z-10 -translate-x-1/2 rounded-full bg-amber-400 px-3 py-1 text-xs font-bold text-emerald-950 whitespace-nowrap">Most popular</div>}<CardHeader><CardTitle className="text-xl">{name}</CardTitle><CardDescription>{desc}</CardDescription><div className="pt-4 text-4xl font-bold">{price}{i === 1 && !annual && <span className="text-sm font-normal text-muted-foreground"> / month</span>}</div></CardHeader><CardContent><ul className="flex flex-col gap-3 text-sm text-muted-foreground">{(items as string[]).map(item => <li key={item} className="flex gap-2"><Check className="text-emerald-600" />{item}</li>)}</ul><Button nativeButton={false} render={<a href="#" />} className={`mt-8 w-full ${i === 1 ? 'bg-amber-500 text-emerald-950 hover:bg-amber-400' : ''}`} variant={i === 1 ? 'default' : 'outline'}>{i === 2 ? 'Talk to us' : 'Get started'} <ArrowRight data-icon="inline-end" /></Button></CardContent></Card>)}</div></section>
      <section className="bg-secondary/40"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="reveal mx-auto max-w-2xl text-center"><p className="eyebrow">People are keeping better books</p><h2 className="section-title">Less chasing. <span>More closing.</span></h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['FA', 'Fahad Ali', 'Director, Greenfield Estates', '“We stopped asking three people for the same payment update. Plot Ledge gives everyone the answer.”'], ['SA', 'Sana Ahmed', 'Accounts, Sunrise Developers', '“The installment view alone saves us hours every week. Our receipts look professional too.”'], ['HR', 'Hamza Raza', 'Plot dealer', '“I can walk into a buyer meeting and know exactly which plots are available. That changes the conversation.”']].map(([initials, name, role, quote]) => <Card key={String(name)} className="reveal border-border bg-card"><CardContent className="pt-7"><p className="leading-7 text-foreground">{quote}</p><div className="mt-7 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-emerald-100 font-semibold text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">{initials}</div><div><p className="text-sm font-semibold">{name}</p><p className="text-xs text-muted-foreground">{role}</p></div></div></CardContent></Card>)}</div></div></section>
      <section id="faq" className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:py-20"><div className="reveal text-center"><p className="eyebrow">Questions, answered</p><h2 className="section-title">Good systems should feel <span>straightforward.</span></h2></div><Accordion className="reveal mt-10">{faqs.map(([question, answer], i) => <AccordionItem key={question} value={`item-${i}`}><AccordionTrigger className="text-left text-base font-semibold">{question}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion></section>
      <section className="contour relative overflow-hidden bg-emerald-950 text-white"><div className="relative mx-auto max-w-7xl px-4 py-16 text-center sm:px-6 lg:py-20"><p className="eyebrow text-amber-300">Your next plot of growth</p><h2 className="mx-auto max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">Bring your business into the clear.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-emerald-100/70">One ledger for every plot, payment, and promise. Start free and see the difference this week.</p><Button size="lg" nativeButton={false} render={<a href="#" />} className="mt-8 bg-amber-400 text-emerald-950 hover:bg-amber-300">Get started free <ArrowRight data-icon="inline-end" /></Button></div></section>
    </main>
    <footer className="bg-emerald-950 text-emerald-100/70"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-14 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr_1fr] lg:px-8"><div><Logo inverse /><p className="mt-5 max-w-xs text-sm leading-6">Every plot. Every payment. One ledger.</p></div>{[['Product', 'Features', 'Pricing', 'Roadmap'], ['Company', 'About', 'Contact', 'Careers'], ['Resources', 'Help center', 'Guides', 'Status']].map(([heading, ...links]) => <div key={String(heading)}><h3 className="mb-4 text-sm font-semibold text-white">{heading}</h3><div className="flex flex-col gap-3 text-sm">{links.map(link => <a href={link === 'Features' ? '#features' : link === 'Pricing' ? '#pricing' : '#'} key={link} className="transition-colors hover:text-white">{link}</a>)}</div></div>)}</div><div className="mx-auto flex max-w-7xl flex-col gap-4 border-t border-white/10 px-4 py-6 text-xs sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© 2026 Plot Ledge. Built for people who build places.</span><div className="flex items-center gap-4"><a href="#" aria-label="LinkedIn" className="hover:text-white"><LinkedinIcon /></a><a href="#" aria-label="X (Twitter)" className="hover:text-white"><XIcon /></a><a href="#" aria-label="Instagram" className="hover:text-white"><InstagramIcon /></a></div></div></footer>
  </div>
}
